fastlane_version "2.59.0"

default_platform :mac

platform :mac do
  desc "Runs all the tests"
  lane :test do
    scan(output_types: "junit")
  end
  lane :release do
    increment_build_number(xcodeproj: 'SeaEye.xcodeproj') # version bump
  end
end
